/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BulkGitlabRouteImport } from './routes/bulk-gitlab'
import { Route as AppIconMakerRouteImport } from './routes/app-icon-maker'
import { Route as IndexRouteImport } from './routes/index'

const BulkGitlabRoute = BulkGitlabRouteImport.update({
  id: '/bulk-gitlab',
  path: '/bulk-gitlab',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIconMakerRoute = AppIconMakerRouteImport.update({
  id: '/app-icon-maker',
  path: '/app-icon-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-icon-maker': typeof AppIconMakerRoute
  '/bulk-gitlab': typeof BulkGitlabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-icon-maker': typeof AppIconMakerRoute
  '/bulk-gitlab': typeof BulkGitlabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-icon-maker': typeof AppIconMakerRoute
  '/bulk-gitlab': typeof BulkGitlabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app-icon-maker' | '/bulk-gitlab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app-icon-maker' | '/bulk-gitlab'
  id: '__root__' | '/' | '/app-icon-maker' | '/bulk-gitlab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppIconMakerRoute: typeof AppIconMakerRoute
  BulkGitlabRoute: typeof BulkGitlabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bulk-gitlab': {
      id: '/bulk-gitlab'
      path: '/bulk-gitlab'
      fullPath: '/bulk-gitlab'
      preLoaderRoute: typeof BulkGitlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-icon-maker': {
      id: '/app-icon-maker'
      path: '/app-icon-maker'
      fullPath: '/app-icon-maker'
      preLoaderRoute: typeof AppIconMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppIconMakerRoute: AppIconMakerRoute,
  BulkGitlabRoute: BulkGitlabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
